feature_engineering:
  train_ratio: 0.7
  test_ratio: 0.3
  seed: 42
  primary_key: "Transaction_ID"
  target_column: "Is_Fraud"
  features:
    - Transaction_Amount
    - Account_Balance

model_params:
  n_estimators: 50
  max_depth: 5
  random_state: 42
  model_name: "fraud_model_rf_sklearn"
  alias: "inference"

serving_params:
  endpoint_name: "fraud_detection_endpoint_sklearn"
  workload_size: "SMALL"
  scale_to_zero: true